on:
  push:
    branches:
      - main  # Or any other branch from which you want to distribute builds

jobs:
  firebase_distribution:
    runs-on: ubuntu-latest  # Can be any supported runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build debug
        run: ./gradlew assembleDebug

      - name: Upload and Distribute App
        uses: mastersam07/firebase-app-distribution-action@v0.1
        with:
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{secrets.FIREBASE_TOKEN}}
          file: 'app/build/intermediates/apk/debug/app-debug.apk'  # e.g., './build/app/outputs/flutter-apk/app-release.apk'
          groups: 'testing-group'  # Optional: distribution groups
